services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - mental-backend
    env_file:
      - ./client/.env
    networks:
      - mental-network

  mental-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - pgvector
    networks:
      - mental-network

  pgvector:
    image: pgvector/pgvector:pg17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./server/db_seed.sql:/docker-entrypoint-initdb.d/db_seed.sql
    networks:
      - mental-network

volumes:
  mentaldata:

networks:
  mental-network:
    driver: bridge
