services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app  # Sync local changes
      - /app/node_modules  # Prevent overriding node_modules
    depends_on:
      - mental-backend
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    env_file:
      - ./client/.env
    networks:
      - mental-network

  mental-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app  # Sync local changes
    environment:
      - DEBUG=True
    depends_on:
      pgvector:
        condition: service_healthy  
    networks:
      - mental-network

  pgvector:
    image: pgvector/pgvector:pg17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./server/db_seed.sql:/docker-entrypoint-initdb.d/db_seed.sql
    networks:
      - mental-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  mentaldata:

networks:
  mental-network:
    driver: bridge
